name: itch.io upload

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1
        with:
          godot-version: 4.2.2
          godot-channel: stable

      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: html5
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: Zabax32
          game: asteroid-deportation-service
          channel: html5
